name: Test module

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go_version: ['1.16', '1.17', '1.18']

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 1
        
      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go_version }}

      - name: Run tests
        run: go test ./...